server:
  port: 9000

netty:
  port: 9001
  idle-timeout: 120

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
